"""Agregar columna aprendiz_id_aprendiz a empresa

Revision ID: 088590aea17d
Revises: ad67b34e3af0
Create Date: 2026-01-13 13:55:39.833517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088590aea17d'
down_revision = 'ad67b34e3af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aprendiz', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('aprendiz_celular_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('aprendiz_correo_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('aprendiz_documento_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_aprendiz_celular'), ['celular'], unique=True)
        batch_op.create_index(batch_op.f('ix_aprendiz_correo'), ['correo'], unique=True)
        batch_op.create_index(batch_op.f('ix_aprendiz_documento'), ['documento'], unique=True)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aprendiz_id_aprendiz', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('empresa_nit_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_empresa_nit'), ['nit'], unique=True)
        batch_op.create_foreign_key(None, 'aprendiz', ['aprendiz_id_aprendiz'], ['id_aprendiz'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_empresa_nit'))
        batch_op.create_unique_constraint(batch_op.f('empresa_nit_key'), ['nit'])
        batch_op.drop_column('aprendiz_id_aprendiz')

    with op.batch_alter_table('aprendiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aprendiz_documento'))
        batch_op.drop_index(batch_op.f('ix_aprendiz_correo'))
        batch_op.drop_index(batch_op.f('ix_aprendiz_celular'))
        batch_op.create_unique_constraint(batch_op.f('aprendiz_documento_key'), ['documento'])
        batch_op.create_unique_constraint(batch_op.f('aprendiz_correo_key'), ['correo'])
        batch_op.create_unique_constraint(batch_op.f('aprendiz_celular_key'), ['celular'])

    # ### end Alembic commands ###
