"""Cambiar sede_id de Aprendiz a nullable=False

Revision ID: fe0197d0faf4
Revises: 088590aea17d
Create Date: 2026-01-13 15:08:50.919486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0197d0faf4'
down_revision = '088590aea17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero, asignar sede_id por defecto a los que son NULL (asumiendo sede 1 existe)
    op.execute("UPDATE aprendiz SET sede_id = 1 WHERE sede_id IS NULL")

    with op.batch_alter_table('aprendiz', schema=None) as batch_op:
        batch_op.alter_column('sede_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aprendiz', schema=None) as batch_op:
        batch_op.alter_column('sede_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
